beginseg
    name "ovl_Rat"
    include "build/src/overlays/actors/hm_pack/ovl_Rat/rat.o"
    include "build/src/overlays/actors/hm_pack/ovl_Rat/ovl_Rat_reloc.o"
endseg

beginseg
    name "ovl_Metal_Crate"
    include "build/src/overlays/actors/hm_pack/ovl_Metal_Crate/metal_crate.o"
    include "build/src/overlays/actors/hm_pack/ovl_Metal_Crate/ovl_Metal_Crate_reloc.o"
endseg

beginseg
    name "ovl_Invisible_Trigger_Switch"
    include "build/src/overlays/actors/hm_pack/ovl_Invisible_Trigger_Switch/invisible_trigger_switch.o"
    include "build/src/overlays/actors/hm_pack/ovl_Invisible_Trigger_Switch/ovl_Invisible_Trigger_Switch_reloc.o"
endseg

beginseg
    name "ovl_En_Zol"
    include "build/src/overlays/actors/hm_pack/ovl_En_Zol/z_en_zol.o"
    include "build/src/overlays/actors/hm_pack/ovl_En_Zol/ovl_En_Zol_reloc.o"
endseg

beginseg
    name "ovl_Hammer_Peg"
    include "build/src/overlays/actors/hm_pack/ovl_Hammer_Peg/hammer_peg.o"
    include "build/src/overlays/actors/hm_pack/ovl_Hammer_Peg/ovl_Hammer_Peg_reloc.o"
endseg

beginseg
    name "ovl_Ladder"
    include "build/src/overlays/actors/hm_pack/ovl_Ladder/ladder.o"
    include "build/src/overlays/actors/hm_pack/ovl_Ladder/ovl_Ladder_reloc.o"
endseg

beginseg
    name "ovl_En_Wiz"
    include "build/src/overlays/actors/hm_pack/ovl_En_Wiz/z_en_wiz.o"
    include "build/src/overlays/actors/hm_pack/ovl_En_Wiz/ovl_En_Wiz_reloc.o"
endseg

beginseg
    name "ovl_En_Wiz_Fire"
    include "build/src/overlays/actors/hm_pack/ovl_En_Wiz/z_en_wiz_fire.o"
    include "build/src/overlays/actors/hm_pack/ovl_En_Wiz/ovl_En_Wiz_Fire_reloc.o"
endseg

beginseg
    name "ovl_Floor_Spikes"
    include "build/src/overlays/actors/hm_pack/ovl_Floor_Spikes/floor_spikes.o"
    include "build/src/overlays/actors/hm_pack/ovl_Floor_Spikes/ovl_Floor_Spikes_reloc.o"
endseg

beginseg
    name "ovl_Pols_Voice"
    include "build/src/overlays/actors/hm_pack/ovl_Pols_Voice/pols_voice.o"
    include "build/src/overlays/actors/hm_pack/ovl_Pols_Voice/ovl_Pols_Voice_reloc.o"
endseg

beginseg
    name "ovl_Jumptoggle_Platform"
    include "build/src/overlays/actors/hm_pack/ovl_Jumptoggle_Platform/jumptoggle_platform.o"
    include "build/src/overlays/actors/hm_pack/ovl_Jumptoggle_Platform/ovl_Jumptoggle_Platform_reloc.o"
endseg

beginseg
    name "ovl_Platforms"
    include "build/src/overlays/actors/hm_pack/ovl_Platforms/platforms.o"
    include "build/src/overlays/actors/hm_pack/ovl_Platforms/ovl_Platforms_reloc.o"
endseg

beginseg
    name "ovl_Wall_Pull_Switch"
    include "build/src/overlays/actors/hm_pack/ovl_Wall_Pull_Switch/wall_pull_switch.o"
    include "build/src/overlays/actors/hm_pack/ovl_Wall_Pull_Switch/ovl_Wall_Pull_Switch_reloc.o"
endseg

beginseg
    name "ovl_Obj_Fan"
    include "build/src/overlays/actors/hm_pack/ovl_Obj_Fan/z_obj_fan.o"
    include "build/src/overlays/actors/hm_pack/ovl_Obj_Fan/ovl_Obj_Fan_reloc.o"
endseg
