beginseg
    name "object_rat"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_rat/rat_skel.o"
    include "build/assets_hm_pack/objects/object_rat/rat_anim_attack.o"
    include "build/assets_hm_pack/objects/object_rat/rat_anim_damaged.o"
    include "build/assets_hm_pack/objects/object_rat/rat_anim_death.o"
    include "build/assets_hm_pack/objects/object_rat/rat_anim_endrun.o"
    include "build/assets_hm_pack/objects/object_rat/rat_anim_idle.o"
    include "build/assets_hm_pack/objects/object_rat/rat_anim_notice.o"
    include "build/assets_hm_pack/objects/object_rat/rat_anim_run.o"
    include "build/assets_hm_pack/objects/object_rat/rat_anim_startrun.o"
    number 6
endseg

beginseg
    name "object_metal_crate"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_metal_crate/object_metal_crate.o"
    number 6
endseg

beginseg
    name "object_zol"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_zol/object_zol.o"
    number 6
endseg

beginseg
    name "object_hammer_peg"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_hammer_peg/hammer_peg_base_model.o"
    include "build/assets_hm_pack/objects/object_hammer_peg/hammer_peg_top_model.o"
    include "build/assets_hm_pack/objects/object_hammer_peg/hammer_peg_base_col.o"
    number 6
endseg

beginseg
    name "object_ladder"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_ladder/ladder_medium_model.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_medium_col.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_small_model.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_small_col.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_large_model.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_large_col.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_metal_medium_model.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_metal_medium_col.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_metal_small_model.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_metal_small_col.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_metal_large_model.o"
    include "build/assets_hm_pack/objects/object_ladder/ladder_metal_large_col.o"
    number 6
endseg

beginseg
    name "object_wiz"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_wiz/object_wiz.o"
    number 6
endseg

beginseg
    name "object_floor_spikes"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_floor_spikes/floor_spike_base_small_col.o"
    include "build/assets_hm_pack/objects/object_floor_spikes/floor_spike_base_small_model.o"
    include "build/assets_hm_pack/objects/object_floor_spikes/floor_spike_spikes_small_model.o"
    include "build/assets_hm_pack/objects/object_floor_spikes/floor_spike_base_medium_col.o"
    include "build/assets_hm_pack/objects/object_floor_spikes/floor_spike_base_medium_model.o"
    include "build/assets_hm_pack/objects/object_floor_spikes/floor_spike_spikes_medium_model.o"
    include "build/assets_hm_pack/objects/object_floor_spikes/floor_spike_base_large_col.o"
    include "build/assets_hm_pack/objects/object_floor_spikes/floor_spike_base_large_model.o"
    include "build/assets_hm_pack/objects/object_floor_spikes/floor_spike_spikes_large_model.o"
    number 6
endseg

beginseg
    name "object_pols_voice"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_pols_voice/pols_voice_skel.o"
    include "build/assets_hm_pack/objects/object_pols_voice/pols_voice_anim_idle.o"
    include "build/assets_hm_pack/objects/object_pols_voice/pols_voice_anim_hop.o"
    include "build/assets_hm_pack/objects/object_pols_voice/pols_voice_anim_grab.o"
    include "build/assets_hm_pack/objects/object_pols_voice/pols_voice_anim_damaged.o"
    include "build/assets_hm_pack/objects/object_pols_voice/pols_voice_anim_die.o"
    number 6
endseg

beginseg
    name "object_jumptoggle_platform"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_jumptoggle_platform/object_jumptoggle_platform.o"
    number 6
endseg

beginseg
    name "object_platforms"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_platforms/platform_cone_grass_model.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_cone_grass_col.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_hex_grass_model.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_hex_grass_col.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_hex_ice_model.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_hex_ice_col.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_square_grass_model.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_square_grass_col.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_square_stone_model.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_square_stone_checkermodel.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_square_stone_col.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_square_wood_model.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_square_wood_checkermodel.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_square_wood_col.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_square_ice_model.o"
    include "build/assets_hm_pack/objects/object_platforms/platform_square_ice_col.o"
    number 6
endseg

beginseg
    name "object_wall_pull_switch"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_wall_pull_switch/object_wall_pull_switch.o"
    number 6
endseg

beginseg
    name "object_fan"
    romalign 0x1000
    include "build/assets_hm_pack/objects/object_fan/object_fan.o"
    include "build/assets_hm_pack/objects/object_fan/gWindDL.o"
    number 6
endseg
