extern SurfaceType gJumpTogglePlatformCol_polygonTypes[];
extern CollisionPoly gJumpTogglePlatformCol_polygons[];
extern Vec3s gJumpTogglePlatformCol_vertices[12];
extern CollisionHeader gJumpTogglePlatformCol_collisionHeader;
