#ifndef OBJECT_WIZ_H
#define OBJECT_WIZ_H 1

extern u64 gWizrobeIceSmokeTex[];
extern u64 gWizrobeIceSmokeMaskTex[];
extern Vtx object_wizVtx_000E40[];
extern Gfx gWizrobeIceSmokeMaterialDL[];
extern Gfx gWizrobeIceSmokeModelDL[];
extern Vtx object_wizVtx_0016C0[];
extern Vtx object_wizVtx_002600[];
extern Gfx gWizrobeSmallFlameDL[];
extern u64 gWizrobeSmallFlameTex[];
extern u64 gWizrobeSmallFlameMaskTex[];
extern Vtx object_wizVtx_002B10[];
extern Gfx gWizrobeMagicProjectileDL[];
extern u64 gWizrobeMagicProjectileTex[];
extern u64 gWizrobeFirePoolTex[];
extern Vtx object_wizVtx_003000[];
extern Gfx gWizrobeFirePoolDL[];
extern u64 gWizrobeFireSmokeTex[];
extern Vtx object_wizVtx_0035E0[];
extern Gfx gWizrobeFireSmokeDL[];
extern u64 gWizrobeBigFlameTex[];
extern u64 gWizrobeBigFlameMaskTex[];
extern Vtx object_wizVtx_003F00[];
extern Gfx gWizrobeBigFlameDL[];
extern u64 gWizrobeIcePoolTex[];
extern Vtx gWizrobeUnusedVtx[];
extern Vtx object_wizVtx_0050F0[];
extern Gfx gWizrobeIcePoolDL[];
extern u64 gWizrobeIcePoolShineTex[];
extern u64 gWizrobeIcePoolShineMaskTex[];
extern Vtx object_wizVtx_0056B0[];
extern Gfx gWizrobeIcePoolShineDL[];
extern Vtx object_wizVtx_005830[];

extern u64 Armature_cloth3_i8[];
extern u64 Armature_cloth_white_ia8[];
extern u64 Armature_jewel2_ci8[];
extern u64 Armature_jewel2_ci8_pal_rgba16[];
extern u64 Armature_hemd3_ci8[];
extern u64 Armature_hemd3_ci8_pal_rgba16[];
extern u64 Armature_skin2_ci8[];
extern u64 Armature_skin2_ci8_pal_rgba16[];
extern u64 Armature_transition_ci8[];
extern u64 Armature_transition_ci8_pal_rgba16[];
extern u64 Armature_tongue_ci8[];
extern u64 Armature_tongue_ci8_pal_rgba16[];
extern u64 Armature_beak_ci8[];
extern u64 Armature_beak_ci8_pal_rgba16[];
extern u64 Armature_eye4_ci8[];
extern u64 Armature_eye4_ci8_pal_rgba16[];
extern u64 Armature_GTG_0x4D900_32x32_CI8_ci8[];
extern u64 Armature_GTG_0x4D900_32x32_CI8_ci8_pal_rgba16[];
extern u64 Armature_wand_ci8[];
extern u64 Armature_wand_ci8_pal_rgba16[];
extern Vtx Armature_Bone_mesh_layer_Opaque_vtx_0[16];
extern Gfx Armature_Bone_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_Bone_mesh_layer_Opaque_vtx_1[12];
extern Gfx Armature_Bone_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_Bone_001_mesh_layer_Opaque_vtx_0[6];
extern Gfx Armature_Bone_001_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_Bone_001_mesh_layer_Opaque_vtx_1[48];
extern Gfx Armature_Bone_001_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_Bone_002_mesh_layer_Opaque_vtx_0[50];
extern Gfx Armature_Bone_002_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_Bone_002_mesh_layer_Opaque_vtx_1[9];
extern Gfx Armature_Bone_002_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_Bone_002_mesh_layer_Opaque_vtx_2[6];
extern Gfx Armature_Bone_002_mesh_layer_Opaque_tri_2[];
extern Vtx Armature_Bone_002_mesh_layer_Opaque_vtx_3[9];
extern Gfx Armature_Bone_002_mesh_layer_Opaque_tri_3[];
extern Vtx Armature_Bone_002_mesh_layer_Opaque_vtx_4[16];
extern Gfx Armature_Bone_002_mesh_layer_Opaque_tri_4[];
extern Vtx Armature_Bone_002_mesh_layer_Opaque_vtx_5[8];
extern Gfx Armature_Bone_002_mesh_layer_Opaque_tri_5[];
extern Vtx Armature_lowerjaw_mesh_layer_Opaque_vtx_0[8];
extern Gfx Armature_lowerjaw_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_lowerjaw_mesh_layer_Opaque_vtx_1[14];
extern Gfx Armature_lowerjaw_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_lowerjaw_mesh_layer_Opaque_vtx_2[10];
extern Gfx Armature_lowerjaw_mesh_layer_Opaque_tri_2[];
extern Vtx Armature_upperarm_l_mesh_layer_Opaque_vtx_0[9];
extern Gfx Armature_upperarm_l_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_upperarm_l_mesh_layer_Opaque_vtx_1[18];
extern Gfx Armature_upperarm_l_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_forearm_l_mesh_layer_Opaque_vtx_0[24];
extern Gfx Armature_forearm_l_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_upperarm_r_mesh_layer_Opaque_vtx_0[9];
extern Gfx Armature_upperarm_r_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_upperarm_r_mesh_layer_Opaque_vtx_1[24];
extern Gfx Armature_upperarm_r_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_forearm_r_mesh_layer_Opaque_vtx_0[22];
extern Gfx Armature_forearm_r_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_staff_r_mesh_layer_Opaque_vtx_0[11];
extern Gfx Armature_staff_r_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_staff_r_mesh_layer_Opaque_vtx_1[16];
extern Gfx Armature_staff_r_mesh_layer_Opaque_tri_1[];
extern Gfx mat_Armature_f3dlite_material_021_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_022_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_017_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_018_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_015_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_014_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_019_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_013_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_016_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_024_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_025_layerOpaque[];
extern Gfx Armature_Bone_mesh_layer_Opaque[];
extern Gfx Armature_Bone_001_mesh_layer_Opaque[];
extern Gfx Armature_Bone_002_mesh_layer_Opaque[];
extern Gfx Armature_lowerjaw_mesh_layer_Opaque[];
extern Gfx Armature_upperarm_l_mesh_layer_Opaque[];
extern Gfx Armature_forearm_l_mesh_layer_Opaque[];
extern Gfx Armature_upperarm_r_mesh_layer_Opaque[];
extern Gfx Armature_forearm_r_mesh_layer_Opaque[];
extern Gfx Armature_staff_r_mesh_layer_Opaque[];
extern FlexSkeletonHeader Armature;
#define ARMATURE_LOWERBODY_POS_LIMB 0
#define ARMATURE_BONE_ROT_LIMB 1
#define ARMATURE_UPPERBODY_LIMB 2
#define ARMATURE_HEAD_LIMB 3
#define ARMATURE_LOWERJAW_LIMB 4
#define ARMATURE_COLLAR_L_LIMB 5
#define ARMATURE_UPPERARM_L_LIMB 6
#define ARMATURE_FOREARM_L_LIMB 7
#define ARMATURE_COLLAR_R_LIMB 8
#define ARMATURE_UPPERARM_R_LIMB 9
#define ARMATURE_FOREARM_R_LIMB 10
#define ARMATURE_STAFF_R_LIMB 11
#define ARMATURE_NUM_LIMBS 12

extern AnimationHeader IdleAnim;
extern AnimationHeader AttackAnim;
extern AnimationHeader WindupAnim;
extern AnimationHeader DamageAnim;
extern AnimationHeader EnemyAnim;

#endif
