extern SurfaceType gLadderMetalLargeCol_polygonTypes[];
extern CollisionPoly gLadderMetalLargeCol_polygons[];
extern Vec3s gLadderMetalLargeCol_vertices[12];
extern CollisionHeader gLadderMetalLargeCol_collisionHeader;
