extern u64 gPolsVoiceSkel_PolsVoice_Fur_00_ci8[];
extern u64 gPolsVoiceSkel_PolsVoice_Fur_00_pal_rgba16[];
extern u64 gPolsVoiceSkel_PolsVoice_Tooth_00_ci8[];
extern u64 gPolsVoiceSkel_PolsVoice_Tooth_00_pal_rgba16[];
extern u64 gPolsVoiceSkel_PolsVoice_Nose_00_ci8[];
extern u64 gPolsVoiceSkel_PolsVoice_Nose_00_pal_rgba16[];
extern u64 gPolsVoiceSkel_PolsVoice_Eye_00_ci8[];
extern u64 gPolsVoiceSkel_PolsVoice_Eye_00_pal_rgba16[];
extern u64 gPolsVoiceSkel_PolsVoice_Ear_00_ci8[];
extern u64 gPolsVoiceSkel_PolsVoice_Ear_00_pal_rgba16[];
extern u64 gPolsVoiceSkel_PolsVoice_Whisker_00_ia8[];
extern Vtx gPolsVoiceSkel_LowerBody_mesh_layer_Opaque_vtx_0[18];
extern Gfx gPolsVoiceSkel_LowerBody_mesh_layer_Opaque_tri_0[];
extern Vtx gPolsVoiceSkel_LowerBody_mesh_layer_Opaque_vtx_1[96];
extern Gfx gPolsVoiceSkel_LowerBody_mesh_layer_Opaque_tri_1[];
extern Vtx gPolsVoiceSkel_UpperBody_mesh_layer_Opaque_vtx_0[21];
extern Gfx gPolsVoiceSkel_UpperBody_mesh_layer_Opaque_tri_0[];
extern Vtx gPolsVoiceSkel_UpperBody_mesh_layer_Opaque_vtx_1[11];
extern Gfx gPolsVoiceSkel_UpperBody_mesh_layer_Opaque_tri_1[];
extern Vtx gPolsVoiceSkel_Head_mesh_layer_Opaque_vtx_0[58];
extern Gfx gPolsVoiceSkel_Head_mesh_layer_Opaque_tri_0[];
extern Vtx gPolsVoiceSkel_Head_mesh_layer_Opaque_vtx_1[10];
extern Gfx gPolsVoiceSkel_Head_mesh_layer_Opaque_tri_1[];
extern Vtx gPolsVoiceSkel_Head_mesh_layer_Opaque_vtx_2[6];
extern Gfx gPolsVoiceSkel_Head_mesh_layer_Opaque_tri_2[];
extern Vtx gPolsVoiceSkel_Head_mesh_layer_Opaque_vtx_3[9];
extern Gfx gPolsVoiceSkel_Head_mesh_layer_Opaque_tri_3[];
extern Vtx gPolsVoiceSkel_Head_mesh_layer_Opaque_vtx_4[8];
extern Gfx gPolsVoiceSkel_Head_mesh_layer_Opaque_tri_4[];
extern Vtx gPolsVoiceSkel_Ear_L_mesh_layer_Opaque_vtx_0[14];
extern Gfx gPolsVoiceSkel_Ear_L_mesh_layer_Opaque_tri_0[];
extern Vtx gPolsVoiceSkel_Ear_L_mesh_layer_Opaque_vtx_1[6];
extern Gfx gPolsVoiceSkel_Ear_L_mesh_layer_Opaque_tri_1[];
extern Vtx gPolsVoiceSkel_Ear_R_mesh_layer_Opaque_vtx_0[14];
extern Gfx gPolsVoiceSkel_Ear_R_mesh_layer_Opaque_tri_0[];
extern Vtx gPolsVoiceSkel_Ear_R_mesh_layer_Opaque_vtx_1[6];
extern Gfx gPolsVoiceSkel_Ear_R_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gPolsVoiceSkel_Fur_layerOpaque[];
extern Gfx mat_gPolsVoiceSkel_Teeth_layerOpaque[];
extern Gfx mat_gPolsVoiceSkel_Nose_layerOpaque[];
extern Gfx mat_gPolsVoiceSkel_Eyes_layerOpaque[];
extern Gfx mat_gPolsVoiceSkel_Ear_layerOpaque[];
extern Gfx mat_gPolsVoiceSkel_Whiskers_layerOpaque[];
extern Gfx gPolsVoiceSkel_LowerBody_mesh_layer_Opaque[];
extern Gfx gPolsVoiceSkel_UpperBody_mesh_layer_Opaque[];
extern Gfx gPolsVoiceSkel_Head_mesh_layer_Opaque[];
extern Gfx gPolsVoiceSkel_Ear_L_mesh_layer_Opaque[];
extern Gfx gPolsVoiceSkel_Ear_R_mesh_layer_Opaque[];
extern FlexSkeletonHeader gPolsVoiceSkel;
#define GPOLSVOICESKEL_ROOT_POS_LIMB 0
#define GPOLSVOICESKEL_ROOT_ROT_LIMB 1
#define GPOLSVOICESKEL_LOWERBODY_LIMB 2
#define GPOLSVOICESKEL_UPPERBODY_LIMB 3
#define GPOLSVOICESKEL_HEAD_LIMB 4
#define GPOLSVOICESKEL_EAR_L_LIMB 5
#define GPOLSVOICESKEL_EAR_R_LIMB 6
#define GPOLSVOICESKEL_NUM_LIMBS 7
