extern u64 gMetalCrateFragmentDL_metal_crate_ci4[];
extern u64 gMetalCrateFragmentDL_metal_crate_ci4_pal_rgba16[];
extern Vtx gMetalCrateFragmentDL_gMetalCrateFragmentDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gMetalCrateFragmentDL_gMetalCrateFragmentDL_mesh_layer_Opaque_vtx_0[4];
extern Gfx gMetalCrateFragmentDL_gMetalCrateFragmentDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gMetalCrateFragmentDL_metal_fragment_layerOpaque[];
extern Gfx gMetalCrateFragmentDL[];
