extern u64 gRatSkel_Rat_Fur_01_ci8[];
extern u64 gRatSkel_Rat_Fur_01_pal_rgba16[];
extern u64 gRatSkel_Rat_Eye_00_ci8[];
extern u64 gRatSkel_Rat_Eye_00_pal_rgba16[];
extern u64 gRatSkel_Rat_Nose_00_ci8[];
extern u64 gRatSkel_Rat_Nose_00_pal_rgba16[];
extern u64 gRatSkel_Rat_Ear_00_ci8[];
extern u64 gRatSkel_Rat_Ear_00_pal_rgba16[];
extern u64 gRatSkel_Rat_Tooth_00_ci8[];
extern u64 gRatSkel_Rat_Tooth_00_pal_rgba16[];
extern u64 gRatSkel_Rat_Whisker_00_ia8[];
extern Vtx gRatSkel_Body_mesh_layer_Opaque_vtx_0[15];
extern Gfx gRatSkel_Body_mesh_layer_Opaque_tri_0[];
extern Vtx gRatSkel_Arm_L_mesh_layer_Opaque_vtx_0[9];
extern Gfx gRatSkel_Arm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gRatSkel_Hand_L_mesh_layer_Opaque_vtx_0[7];
extern Gfx gRatSkel_Hand_L_mesh_layer_Opaque_tri_0[];
extern Vtx gRatSkel_Arm_R_mesh_layer_Opaque_vtx_0[9];
extern Gfx gRatSkel_Arm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gRatSkel_Hand_R_mesh_layer_Opaque_vtx_0[7];
extern Gfx gRatSkel_Hand_R_mesh_layer_Opaque_tri_0[];
extern Vtx gRatSkel_Head_mesh_layer_Opaque_vtx_0[14];
extern Gfx gRatSkel_Head_mesh_layer_Opaque_tri_0[];
extern Vtx gRatSkel_Head_mesh_layer_Opaque_vtx_1[6];
extern Gfx gRatSkel_Head_mesh_layer_Opaque_tri_1[];
extern Vtx gRatSkel_Head_mesh_layer_Opaque_vtx_2[22];
extern Gfx gRatSkel_Head_mesh_layer_Opaque_tri_2[];
extern Vtx gRatSkel_Head_mesh_layer_Opaque_vtx_3[8];
extern Gfx gRatSkel_Head_mesh_layer_Opaque_tri_3[];
extern Vtx gRatSkel_Head_mesh_layer_Opaque_vtx_4[18];
extern Gfx gRatSkel_Head_mesh_layer_Opaque_tri_4[];
extern Vtx gRatSkel_Head_mesh_layer_Opaque_vtx_5[8];
extern Gfx gRatSkel_Head_mesh_layer_Opaque_tri_5[];
extern Vtx gRatSkel_Leg_L_mesh_layer_Opaque_vtx_0[10];
extern Gfx gRatSkel_Leg_L_mesh_layer_Opaque_tri_0[];
extern Vtx gRatSkel_Leg_R_mesh_layer_Opaque_vtx_0[10];
extern Gfx gRatSkel_Leg_R_mesh_layer_Opaque_tri_0[];
extern Vtx gRatSkel_Tail_mesh_layer_Opaque_vtx_0[14];
extern Gfx gRatSkel_Tail_mesh_layer_Opaque_tri_0[];
extern Vtx gRatSkel_Tail_mesh_layer_Opaque_vtx_1[5];
extern Gfx gRatSkel_Tail_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gRatSkel_Fur2_layerOpaque[];
extern Gfx mat_gRatSkel_Eye_layerOpaque[];
extern Gfx mat_gRatSkel_Nose_layerOpaque[];
extern Gfx mat_gRatSkel_Ear_layerOpaque[];
extern Gfx mat_gRatSkel_Tooth_layerOpaque[];
extern Gfx mat_gRatSkel_Whiskers_layerOpaque[];
extern Gfx gRatSkel_Body_mesh_layer_Opaque[];
extern Gfx gRatSkel_Arm_L_mesh_layer_Opaque[];
extern Gfx gRatSkel_Hand_L_mesh_layer_Opaque[];
extern Gfx gRatSkel_Arm_R_mesh_layer_Opaque[];
extern Gfx gRatSkel_Hand_R_mesh_layer_Opaque[];
extern Gfx gRatSkel_Head_mesh_layer_Opaque[];
extern Gfx gRatSkel_Leg_L_mesh_layer_Opaque[];
extern Gfx gRatSkel_Leg_R_mesh_layer_Opaque[];
extern Gfx gRatSkel_Tail_mesh_layer_Opaque[];
extern FlexSkeletonHeader gRatSkel;
#define GRATSKEL_ROOT_POS_LIMB 0
#define GRATSKEL_ROOT_ROT_LIMB 1
#define GRATSKEL_BODY_LIMB 2
#define GRATSKEL_ARM_L_LIMB 3
#define GRATSKEL_HAND_L_LIMB 4
#define GRATSKEL_ARM_R_LIMB 5
#define GRATSKEL_HAND_R_LIMB 6
#define GRATSKEL_HEAD_LIMB 7
#define GRATSKEL_LEG_L_LIMB 8
#define GRATSKEL_LEG_R_LIMB 9
#define GRATSKEL_TAIL_LIMB 10
#define GRATSKEL_NUM_LIMBS 11
