extern u64 gPullSwitchFrameDL_PullSwitch_Metal_02_ci8[];
extern u64 gPullSwitchFrameDL_PullSwitch_Metal_02_ci8_pal_rgba16[];
extern Vtx gPullSwitchFrameDL_gPullSwitchFrameDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gPullSwitchFrameDL_gPullSwitchFrameDL_mesh_layer_Opaque_vtx_0[12];
extern Gfx gPullSwitchFrameDL_gPullSwitchFrameDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gPullSwitchFrameDL_Base_layerOpaque[];
extern Gfx gPullSwitchFrameDL[];
